"""First Migration

Revision ID: f2a095c94c5a
Revises: 
Create Date: 2022-08-16 11:41:20.533980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2a095c94c5a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('url_short',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('main_url', sa.String(length=200), nullable=True),
    sa.Column('shorter', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('url_short')
    # ### end Alembic commands ###
